In [55]:
import json
import pandas as pd
from pprint import pprint
from fuzzywuzzy import process

In [56]:
africa_iso_code = pd.read_csv('./africa_iso_codes.csv', dtype={'name': str})
africa_iso_code

                        name 2digit 3digit
0                    Algeria     DZ    DZA
1                     Angola     AO    AGO
2                      Benin     BJ    BEN
3                   Botswana     BW    BWA
4               Burkina Faso     BF    BFA
5                    Burundi     BI    BDI
6                   Cameroon     CM    CMR
7                 Cape Verde     CV    CPV
8   Central African Republic     CF    CAF
9                       Chad     TD    TCD
10                   Comoros     KM    COM
11                     Congo     CG    COG
12                  Djibouti     DJ    DJI
13                     Egypt     EG    EGY
14         Equatorial Guinea     GQ    GNQ
15                   Eritrea     ER    ERI
16                  Ethiopia     ET    ETH
17                     Gabon     GA    GAB
18                    Gambia     GM    GMB
19                     Ghana     GH    GHA
20             Guinea-Bissau     GW    GNB
21                    Guinea     GN    GIN
22               Ivory Coast     CI    CIV
23                     Kenya     KE    KEN
24                   Lesotho     LS    LSO
25                   Liberia     LR    LBR
26                     Libya     LY    LBY
27                Madagascar     MG    MDG
28                    Malawi     MW    MWI
29                      Mali     ML    MLI
30                Mauritania     MR    MRT
31                 Mauritius     MU    MUS
32            Mayotte Island     YT    MYT
33                   Morocco     MA    MAR
34                Mozambique     MZ    MOZ
35                   Namibia    NaN    NAM
36                     Niger     NE    NER
37                   Nigeria     NG    NGA
38     Sao Tome and Principe     ST    STP
39            Reunion Island     RE    REU
40                    Rwanda     RW    RWA
41                   Senegal     SN    SEN
42                Seychelles     SC    SYC
43              Sierra Leone     SL    SLE
44                   Somalia     SO    SOM
45              South Africa     ZA    ZAF
46                St. Helena     SH    SHN
47                     Sudan     SD    SDN
48                 Swaziland     SZ    SWZ
49                  Tanzania     TZ    TZA
50                      Togo     TG    TGO
51                   Tunisia     TN    TUN
52                    Uganda     UG    UGA
53                    Zambia     ZM    ZMB
54                  Zimbabwe     ZW    ZWE
55               South Sudan     SS    SSD
56                  DR Congo     CD    COD

In [57]:
trade_data = pd.read_csv('./cleaned_data_2014.csv', dtype={'commodity_group': str})
trade_data

     commodity_group exporter  export_value  import_value
0                 01      AGO             0             0
1                 01      BDI             0             0
2                 01      BEN             0             0
3                 01      BFA             0             0
4                 01      BWA             0             0
5                 01      CAF             0             0
6                 01      CIV             0             0
7                 01      CMR             0             0
8                 01      COD          6687             0
9                 01      COG             0             0
10                01      COM             0             0
11                01      CPV             0             0
12                01      DJI             0             0
13                01      DZA             0             0
14                01      EGY            71          2220
15                01      ERI             0             0
16                01      ETH             0           654
17                01      GAB             0             0
18                01      GHA         14366             0
19                01      GIN         47715             0
20                01      GMB             0           195
21                01      GNB             0             0
22                01      GNQ             0             0
23                01      KEN             0             0
24                01      LBR             0             0
25                01      LBY             0           200
26                01      LSO             0             0
27                01      MAR             0             0
28                01      MDG             0             0
29                01      MLI         97308             0
...              ...      ...           ...           ...
5111              99      KEN             0             0
5112              99      LBR             0             0
5113              99      LBY             0             0
5114              99      LSO             0             0
5115              99      MAR         16200             0
5116              99      MDG             0             0
5117              99      MLI             0             0
5118              99      MOZ         75000             0
5119              99      MRT             0             0
5120              99      MUS             0             0
5121              99      MWI             0             0
5122              99      NAM             0             0
5123              99      NER             0             0
5124              99      NGA             0             0
5125              99      RWA             0             0
5126              99      SDN             0        185500
5127              99      SEN             0        109470
5128              99      SLE             0             0
5129              99      SOM             0             0
5130              99      STP             0           139
5131              99      SWZ             0             0
5132              99      SYC             0             0
5133              99      TCD             0        661413
5134              99      TGO             0             0
5135              99      TUN             0             0
5136              99      TZA             0        594907
5137              99      UGA             0             0
5138              99      ZAF   25400000000     192000000
5139              99      ZMB         73838        612368
5140              99      ZWE             0        331579

[5141 rows x 4 columns]

In [58]:
product_names = pd.read_csv('./products_prospedia.csv',dtype={'code': str})
product_names = product_names[['code', 'name', 'level']]
product_names = product_names[product_names['level'] == '2digit']

In [59]:
product_names.tail(5)

     code                                               name   level
1312   93  Arms and ammunition; parts and accessories the...  2digit
1320   94  Furniture; bedding, mattresses, mattress suppo...  2digit
1327   95  Toys, games and sports requisites; parts and a...  2digit
1336   96               Miscellaneous manufactured articles.  2digit
1356   97     Works of art, collectors' pieces and antiques.  2digit

In [60]:
merged_data = pd.merge(trade_data, product_names,
              left_on=['commodity_group'],
              right_on=['code'])

In [61]:
merged_data= pd.merge(merged_data, africa_iso_code,
              left_on=['exporter'],
              right_on=['3digit'])

In [62]:
merged_data.rename(columns={'name_x': 'product_name', 'name_y': 'country_name'}, inplace=True)

In [63]:
len(trade_data)

5141

In [64]:
merged_data = merged_data[[
        'commodity_group', 'export_value', 
        'import_value','product_name', 'country_name', 
        '2digit', '3digit']]

In [65]:
merged_data.to_csv('./visualized_data.csv',index=False)